### ISSUE TITLE
installing RML Workbench on Debian

### ISSUE THREAD

**Issue by sebbader** [RMLio/RMLWorkbench#2]
Hi,

I tried to follow the installation instruction in order to deploy the Workbench on my Debian server. Everything worked fine till the last command 'npm start'.
Following error message appears:

    [nodemon] 1.11.0
    [nodemon] to restart at any time, enter `rs`
    [nodemon] watching: *.*
    [nodemon] starting `node app.js`
    Running "watch" task
    Waiting...
    
    util.js:556
      ctor.prototype = Object.create(superCtor.prototype, {
                              ^
    TypeError: Object prototype may only be an Object or null
        at Function.create (native)
        at Object.exports.inherits (util.js:556:27)
        at Object.<anonymous> (/home/sba/RMLWorkbench/drywall-workbench/util/events/events.js:7:6)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (/home/sba/RMLWorkbench/drywall-workbench/app.js:95:23)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Function.Module.runMain (module.js:497:10)
        at startup (node.js:119:16)
    [nodemon] app crashed - waiting for file changes before starting...

I assume it has something to do with package versions, but reinstalling and upgrades did not help:
npm --version
3.10.10
node --version
v0.10.29
npm view grunt version
1.0.1

Any ideas?

Best,
Sebastian

**Comment by pheyvaer** [comment]
I think your node version is too low. Could you try and update to the latest version?

**Comment by sebbader** [comment]
Yes, that was it. Sorry for the inconvenience!
Best,
Sebastian
